apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: "2020-12-15T12:55:03Z"
  generation: 1
  labels:
    app: admission-webhook
    openebs.io/component-name: admission-webhook
    openebs.io/version: 2.3.0
  managedFields:
  - apiVersion: admissionregistration.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
          f:openebs.io/component-name: {}
          f:openebs.io/version: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"a9065a5c-5641-4844-9915-3f8af8f65a6f"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:webhooks:
        .: {}
        k:{"name":"admission-webhook.openebs.io"}:
          .: {}
          f:admissionReviewVersions: {}
          f:clientConfig:
            .: {}
            f:caBundle: {}
            f:service:
              .: {}
              f:name: {}
              f:namespace: {}
              f:path: {}
              f:port: {}
          f:failurePolicy: {}
          f:matchPolicy: {}
          f:name: {}
          f:namespaceSelector: {}
          f:objectSelector: {}
          f:rules: {}
          f:sideEffects: {}
          f:timeoutSeconds: {}
    manager: admission-server
    operation: Update
    time: "2020-12-15T12:55:03Z"
  name: openebs-validation-webhook-cfg
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: openebs-admission-server
    uid: a9065a5c-5641-4844-9915-3f8af8f65a6f
  resourceVersion: "2799"
  uid: 81398934-5e5a-44ea-b1f6-883a26f66552
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0akNDQWNxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFpTVNBd0hnWURWUVFERXhkaFpHMXAKYzNOcGIyNHRjMlZ5ZG1WeUxYTjJZeTFqWVRBZUZ3MHlNREV5TVRVeE1qVTFNRE5hRncwek1ERXlNVE14TWpVMQpNRE5hTUNJeElEQWVCZ05WQkFNVEYyRmtiV2x6YzJsdmJpMXpaWEoyWlhJdGMzWmpMV05oTUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBc3oxaWIvWUF6RDdaaE1LdFNMekpWQytYRlBQWFcyQ00KT050ak1VcE1FYWhvVjNINVhaTWwyZWNZejRzQ2JvM05JVXhLblBEcE5aRWdDV2M3a0x3N3pDSVZHS3hxRmI4SApmSUwvYjViaWtqdWZidjF4dmljRVZZdll4bjE0SXpqSzRvTnFpV2xSU2pxWGVMVlRUT05IcGRtNFlVUHNHSmNuCnBZQTRFM05RMnNGY1QwbktNRE1Ta3g3dW5tb1JYL09RYzFleUwySEwyV3BRZCs3Ykx3VW81NjdJeXdSM0w2SmgKc3F2dGt1RmdyaEFnMTdSNndKemdoQ3NUZHZ3dVVwaWpZUEwxd0tHM0F4aERiZTFFSVJqUmo0dVNpbmZsbXhZRwpIcEpmcmY4VzQ2S3FuN3EvUXh2emQyMU5mVTlMUDFCZzFFM2dCVVllNzlkTjYxVXQ0c09WWVFJREFRQUJveU13CklUQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0YKQUFPQ0FRRUFsYnBzcWpOVVpkSU93enVMbVZnc2h2NHI5L3BHWW55VW9hV0NFaXpwZ1FLRVcxdHhSUlJ2eFExVgpyL1Z4UlVybVVtQTdiRS9BZXQvNEpWd0hyTU8rcnFFNisyS2V3QkxsRWpIUzhueEs2OGtQTUR2OElOTzlub29WCnVkekNydnJsRkE4S0Y4UHhVVFNCQXh2WmNuS3RwRUtnMHF0MnNzb2gxNXBqVUZleGRtZXpyQzBEODdoVGVuU2MKUHNScXNTWE5pUVFtSmI3UUVHbXl3NGdsNG96TTExQkNuS0xIeG9Odmc0VnJYWjBGdWVVVHkvSjNVQ21DZHVvRApDM285c3NWNWN4bVdFNW1ObWZyVWFJVmdsSUtOdm9OVSs1Q3BHQ0R2UTUyNWlsNlRlUFFWWUZlUkRzOFNpTjRHCm1GWXgvaHdHQU9HRDZWbnVmS1hQNFFqOUpJMExydz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: admission-server-svc
      namespace: openebs
      path: /validate
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: admission-webhook.openebs.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - CREATE
    - DELETE
    resources:
    - persistentvolumeclaims
    scope: '*'
  - apiGroups:
    - openebs.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - cstorpoolclusters
    scope: '*'
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - UPDATE
    resources:
    - cstorvolumeclaims
    scope: '*'
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - DELETE
    resources:
    - storagepoolclaims
    scope: '*'
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - DELETE
    resources:
    - namespaces
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 5
