{{- $skipStatic := .Values.skipStatic -}}
{{ if not $skipStatic }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: static
  labels:
    name: devstats
    type: static
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: devstats
        type: static
    spec:
      containers:
      - env:
        image: {{ .Values.staticImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: static
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-service
  labels:
    name: devstats
    type: static-service
spec:
  # type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    name: devstats
    type: static
{{ end }}
