{{- $skipPostgres := .Values.skipPostgres -}}
{{ if not $skipPostgres }}
{{- /*
Postgres RBAC role.
Required for the deployed postgres pods to have control over
configmaps, endpoint and services required to control leader election and failover.
*/ -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ .Values.postgresSvcName }}'
  labels:
    name: devstats
    type: postgres
    cluster-name: '{{ .Values.postgresSvcName }}'
{{ end }}
