{{- $skipPVs := .Values.skipPVs -}}
{{ if not $skipPVs }}
{{- $root := . -}}
{{- range $index, $_ := .Values.projects -}}
{{- if and (or (eq ($index|int) ($root.Values.indexPVsFrom|int)) (gt ($index|int) ($root.Values.indexPVsFrom|int))) (lt ($index|int) ($root.Values.indexPVsTo|int)) -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: '{{ $root.Values.namespace }}'
  name: '{{ $root.Values.pvName }}-{{ .proj }}'
  labels:
    name: devstats
    type: 'pvc'
    proj: {{ .proj }}
spec:
  accessModes:
    - {{ $root.Values.storageAccessModes }}
  storageClassName: {{ $root.Values.storageClass }}
  resources:
    requests:
      storage: {{ .disk }}
{{ end }}
{{ end }}
{{ end }}
