{{- $skipNamespaces := .Values.skipNamespaces -}}
{{ if not $skipNamespaces }}
---
kind: Namespace
apiVersion: v1
metadata:
  name: devstats-test
  labels:
    name: devstats-test
---
kind: Namespace
apiVersion: v1
metadata:
  name: devstats-prod
  labels:
    name: devstats-prod
    {{ end }}
