{{- $skipBackupsPV := .Values.skipBackupsPV -}}
{{ if not $skipBackupsPV }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: '{{ .Values.namespace }}'
  name: '{{ .Values.backupsPVName }}'
  labels:
    name: devstats
    type: pvc
    proj: backups
  annotations:
    volume.alpha.kubernetes.io/storage-class: {{ .Values.backupsStorageClass }}
spec:
  accessModes:
    - {{ .Values.backupsStorageAccessModes }}
  storageClassName: {{ .Values.backupsStorageClass }}
  resources:
    requests:
      storage: {{ .Values.backupsPVSize }}
{{ end }}
